const express = require('express');
const router = express.Router();
const adminController = require('../controladores/admin');

router.get("/grupos", adminController.obtenerGrupos);
router.get("/usuarios", adminController.obtenerUsuarios);
router.get("/mensajes", adminController.obtenerMensajes);
router.get("/fichas", adminController.obtenerFichas);
router.get("/programas", adminController.obtenerProgramas);
router.get("/grupo/:id_grupo", adminController.obtenerUnGrupo);
router.get("/miembros/:id_grupo", adminController.obtenerMiembros);
router.get("/miembro/:numerodoc/:id_grupo", adminController.obtenerMiembro);
router.get("/usuario/:numerodoc", adminController.obtenerUnUsuario);
router.get("/mensaje/:id_mensaje", adminController.obtenerUnMensaje);
router.get("/ubicacion-mensaje/:id_mensaje", adminController.obtenerDatosMensaje);
router.get("/ficha/:id_ficha", adminController.obtenerUnaFicha);
router.get("/grupos/:id_ficha", adminController.obtenerGruposDeFicha);
router.get("/num-fichas", adminController.obtenerFichasId);
router.post("/agregar-ficha", adminController.insertarFicha);
router.post("/agregar-grupo", adminController.insertarGrupo);
router.post("/agregar-miembro", adminController.agregarMiembro);
router.post("/agregar-mensaje", adminController.insertarMensaje);
router.post("/agregar-usuario", adminController.insertarUsuario);
router.post("/miembros-faltantes", adminController.miembrosFaltantes);
router.put("/editar-ficha/:id_ficha", adminController.actualizarFicha);
router.put("/editar-grupo/:id_grupo", adminController.actualizarGrupo);
router.put("/editar-mensaje/:id_mensaje", adminController.actualizarMensaje);
router.put("/editar-usuario/:numerodoc", adminController.actualizarUsuario);
router.put("/eliminar-ficha/:id_ficha", adminController.actualizarFicha);
router.put("/eliminar-grupo/:id_grupo", adminController.actualizarGrupo);
router.put("/eliminar-miembro/:id_ug", adminController.eliminarMiembro);
router.put("/eliminar-mensaje/:id_mensaje", adminController.actualizarMensaje);
router.put("/eliminar-usuario/:numerodoc", adminController.actualizarUsuario);
router.put("/actualizar-miembro/:id_ug", adminController.actualizarMiembro);

module.exports = router;